export const APP_LOADING = "App/APP_LOADING";
export const APP_ERROR = "App/APP_ERROR";
export const SET_DEFERRED_PROMPT = "App/SET_DEFERRED_PROMPT";
export const SET_META = "App/SET_META";
export const SET_URL = "App/SET_URL";
export const ADD_APP_NOTIFICATION = "App/ADD_APP_NOTIFICATION";
export const DELETE_APP_NOTIFICATION = "App/DELETE_APP_NOTIFICATION";
export const SET_TITLE = "App/SET_TITLE";
export const SET_RATES = "App/SET_RATES";
export const SET_RATES_FETCHED_STATUS = "App/SET_RATES_FETCHED_STATUS";
export const SET_DATA_FETCHING_STATUS = "App/SET_DATA_FETCHING_STATUS";
export const SET_SEARCH = "App/SET_SEARCH";
export const SET_SEARCH_FOCUS = "App/SET_SEARCH_FOCUS";
export const SET_SEARCH_RESULTS = "App/SET_SEARCH_RESULTS";
export const SET_SEARCH_RESULTS_LOADING_STATE =
  "App/SET_SEARCH_RESULTS_LOADING_STATE";

export const REDUCER_NAME = "app";
