export const SET_RESET = "Reset/SET_RESET";
export const SET_RESET_MODAL_STATUS = "Reset/SET_RESET_MODAL_STATUS";
export const SET_RESET_ATTEMPTING_STATUS = "Reset/SET_RESET_ATTEMPTING_STATUS";
export const SET_RECOVERY_EMAIL = "Reset/SET_RECOVERY_EMAIL";
export const SET_RECOVERY_NOTICE = "Reset/SET_RECOVERY_NOTICE";
export const REDUCER_NAME = "reset";
