export const SET_HOME = "Home/SET_HOME";
export const SET_SEARCH = "Home/SET_SEARCH";
export const SET_SEARCH_FOCUS = "Home/SET_SEARCH_FOCUS";
export const SET_SEARCH_RESULTS = "Home/SET_SEARCH_RESULTS";
export const SET_SEARCH_RESULTS_LOADING_STATE =
  "Home/SET_SEARCH_RESULTS_LOADING_STATE";
export const SET_HOME_FEED_LOADING_STATE = "Home/SET_HOME_FEED_LOADING_STATE";
export const REDUCER_NAME = "home";
